dist: trusty
sudo: false

# language python, including 3.5, 3.6
language: python
python:
  - "3.5"  
  - "3.6"
  - "nightly"

notifications:
  email:
    recipients:
      - 510662916@qq.com
    on_success: never # default: change
    on_failure: always # default: always

# install tornado module
install:
  - pip install tornado

# test script
script:
  - cd Game_Logic
  - echo "Enter directory Game_Logic"
  - nohup python3 main.py > /dev/null 2>&1 &
  - sleep 1m
  - kill $(ps aux | grep nohup python3 main.py | awk '{ print $0 }')

